[package]
name = "modern-webview-sample"
version = "0.1.0"
authors = ["Brandon Walderman <bwalderman@outlook.com>"]

[dependencies]
modern-webview = { path = "..", version = "0.1.0" }
include_dir = "0.2.1"