[package]
name = "modern-webview-sys"
version = "0.1.0"
authors = ["Brandon Walderman <bwalderman@outlook.com>"]

[lib]
name = "modern_webview_sys"
path = "lib.rs"

[build-dependencies]
cc = "1.0.17"
bindgen = "0.37.0"